### Get all rentals
GET http://localhost:9081/vehicle-rental/api/rentals

### Get single rental
GET http://localhost:9081/vehicle-rental/api/rentals/7625a3cc-df02-4db6-b77f-4b1393733d2a

### Delete rental
DELETE http://localhost:9081/vehicle-rental/api/rentals/7625a3cc-df02-4db6-b77f-4b1393733d2a

### Create rental
PUT http://localhost:9081/vehicle-rental/api/rentals/7625a3cc-df02-4db6-b77f-4b1393733d2a
Content-Type: application/json

{
  "rentalDate": "2023-04-05",
  "returnDate": "2023-04-15",
  "returned": true,
  "user": "7553f71e-5217-4a39-9680-f506d52b08e5",
  "vehicle": "e83dad4d-5d56-4065-8630-8a887536dc41"
}

### Update rental
PATCH http://localhost:9081/vehicle-rental/api/rentals/7625a3cc-df02-4db6-b77f-4b1393733d2a
Content-Type: application/json

{
  "rentalDate": "2023-05-06",
  "returnDate": null,
  "returned": "false"
}

### Get all user rentals
GET http://localhost:9081/vehicle-rental/api/users/7553f71e-5217-4a39-9680-f506d52b08e5/rentals

### Get all vehicle rentals
GET http://localhost:9081/vehicle-rental/api/vehicles/00a1a742-f885-41e1-b37d-92891085b791/rentals