### Get all vehicles
GET http://localhost:9081/vehicle-rental/api/vehicles

### Get single vehicle
GET http://localhost:9081/vehicle-rental/api/vehicles/e83dad4d-5d56-4065-8630-8a887536dc41

### Delete vehicle
DELETE http://localhost:9081/vehicle-rental/api/vehicles/7bf652b9-0760-4aad-9072-b0c2f9f6c138

### Create vehicle
PUT http://localhost:9081/vehicle-rental/api/vehicles/e83dad4d-5d56-4065-8630-8a887536dc41
Content-Type: application/json

{
  "model": "LFA",
  "brand": "Lexus",
  "type": "CAR"
}

### Update vehicle
PATCH http://localhost:9081/vehicle-rental/api/vehicles/e83dad4d-5d56-4065-8630-8a887536dc41
Content-Type: application/json

{
  "model": "Chiron",
  "brand": "Bugatti",
  "type": "CAR"
}
